# Generated by Django 2.1.5 on 2019-11-27 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('myowner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.Member')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
